name: pocket_client
description: A library for authenticating and accessing the Pocket API from Dart
version: 0.1.2
author: Ne4istb <anechytailov@gmail.com>
homepage: https://github.com/Ne4istb/pocket_client
documentation: https://github.com/Ne4istb/pocket_client/blob/master/API.md
environment:
  sdk: '>=1.21.0'
dependencies:
  http: '>=0.11.3+2 <0.12.0'
dev_dependencies:
  test: '>=0.12.0 <0.13.0'
