name: pocket_client
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: Ne4istb <anechytailov@gmail.com>
homepage: https://github.com/Ne4istb

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
